### PR TITLE
fix: compiled page pathname in windows

### LINKED ISSUE #361: Invalid compiled page name in windows on version 1.0.0-canary.1
In next-translate v1.0.0-canary.1, If I have a page in `pages/foo/bar`. The compiled page pathname that need to use in `i18n.json` will be `/foar`.

## Expected behavior
**Page location:** `pages/foo/bar`
**Compiled page pathname:** `/foo/bar`

**Compiled log**
```
next-translate - compiled page: /foo/bar - locale: en - namespaces: common, error - used 
loader: getStaticProps
```

## Actual behavior
**Page location:** `pages/foo/bar`
**Compiled page pathname:** `/foar`

**Compiled log**
```
next-translate - compiled page: /foar - locale: en - namespaces: common, error - used 
loader: getStaticProps
```

### PR DESCRIPTION
**Pull request by vimutti77**
Fixed #361 by replace `\` with `/`

### CODE REVIEW

File: src/plugin/loader.ts [hunk 1]
```diff
@@ -30,7 +30,7 @@ export default function loader(rawCode) {
   // Skip rest of files that are not inside /pages
   if (!this.resourcePath.startsWith(pagesPath)) return rawCode
 
-  const page = this.resourcePath.replace(pagesPath, '/', '')
+  const page = this.resourcePath.replace(pagesPath, '/', '').replace(/\\/g, '/')
```
Comment (aralroca) [inline src/plugin/loader.ts:33]: Nice @vimutti77 good catch!! 🔥 

Here I've did this mistake:

```suggestion
  const page = this.resourcePath.replace(pagesPath, '/').replace(/\\/g, '/')
```

there are only 2 parameters in the `.replace` so this extra parameter doesn't do anything... If you want to take advantage to remove it, perfectly, if not I will remove it.

**Review by aralroca — APPROVED** [review]

**Review by aralroca — APPROVED** [review]
Thanks @vimutti77 ! And welcome to first time contributor!

**Comment by aralroca** [comment]
@allcontributors please add @vimutti77 for code
